### ISSUE TITLE
Updating to latest matter

### ISSUE THREAD

**Issue by Misiur** [demipel8/craftymatter#1]
Hello! Will you mantain this repo further? I forked it and updated some stuff, tho some things are really big changes (Engine.run is deprecated in favor of Runner).

**Comment by demipel8** [comment]
Hello, Sorry for not answering you earlier but this was an experiment for my job and actually... I forgot I had it. I'll check your updates as soon as I can and merge the to the master.

**Comment by demipel8** [comment]
Merge done with master.
